//
// ProfileAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class ProfileAPI {
    /**
     Update My Avatar
     
     - parameter image: (form) Image 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func avatarPost(image: URL, completion: @escaping ((_ data: SuccessResponse?,_ error: Error?) -> Void)) {
        avatarPostWithRequestBuilder(image: image).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Update My Avatar
     - POST /avatar
     - 
     - API Key:
       - type: apiKey x-access-token 
       - name: accessToken
     - API Key:
       - type: apiKey x-api-key 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "result" : true,
  "payload" : {
    "access_token" : "access_token",
    "full_name" : "full_name",
    "avatar_url" : "avatar_url",
    "timezone" : "timezone",
    "last_name" : "last_name",
    "id" : "id",
    "uuid" : "uuid",
    "first_name" : "first_name",
    "email" : "email"
  },
  "message" : "message"
}}]
     
     - parameter image: (form) Image 

     - returns: RequestBuilder<ProfileUpdateMyAvatarResponse> 
     */
    open class func avatarPostWithRequestBuilder(image: URL) -> RequestBuilder<SuccessResponse> {
        let path = "/avatar"
        let URLString = SwaggerClientAPI.basePath + path
        let formParams: [String:Any?] = [
            "image": image
        ]

        let nonNullParameters = APIHelper.rejectNil(formParams)
        let parameters = APIHelper.convertBoolToString(nonNullParameters)
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<SuccessResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     My Profile
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func profileGet(completion: @escaping ((_ data: SuccessResponse?,_ error: Error?) -> Void)) {
        profileGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     My Profile
     - GET /profile
     - Get currently logged in user's profile
     - API Key:
       - type: apiKey x-access-token 
       - name: accessToken
     - API Key:
       - type: apiKey x-api-key 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "result" : true,
  "payload" : {
    "access_token" : "access_token",
    "full_name" : "full_name",
    "avatar_url" : "avatar_url",
    "timezone" : "timezone",
    "last_name" : "last_name",
    "id" : "id",
    "uuid" : "uuid",
    "first_name" : "first_name",
    "email" : "email"
  },
  "message" : "message"
}}]

     - returns: RequestBuilder<ProfileMyProfileResponse> 
     */
    open class func profileGetWithRequestBuilder() -> RequestBuilder<SuccessResponse> {
        let path = "/profile"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<SuccessResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Update My Profile
     
     - parameter body: (body) User 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func profilePut(body: [String: Any], completion: @escaping ((_ data: SuccessResponse?,_ error: Error?) -> Void)) {
        profilePutWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Update My Profile
     - PUT /profile
     - 
     - API Key:
       - type: apiKey x-access-token 
       - name: accessToken
     - API Key:
       - type: apiKey x-api-key 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "result" : true,
  "payload" : {
    "access_token" : "access_token",
    "full_name" : "full_name",
    "avatar_url" : "avatar_url",
    "timezone" : "timezone",
    "last_name" : "last_name",
    "id" : "id",
    "uuid" : "uuid",
    "first_name" : "first_name",
    "email" : "email"
  },
  "message" : "message"
}}]
     
     - parameter body: (body) User 

     - returns: RequestBuilder<ProfileUpdateMyProfileResponse> 
     */
    open class func profilePutWithRequestBuilder(body: [String: Any]) -> RequestBuilder<SuccessResponse> {
        let path = "/profile"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<SuccessResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
