//
// Paginator.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Paginator: Codable {

    public var currentPage: Double?
    public var perPage: Double?
    public var to: Double?

    public init(currentPage: Double?, perPage: Double?, to: Double?) {
        self.currentPage = currentPage
        self.perPage = perPage
        self.to = to
    }

    public enum CodingKeys: String, CodingKey { 
        case currentPage = "current_page"
        case perPage = "per_page"
        case to
    }


}

