//
// Settings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Settings: Codable {

    public var ABOUT_US: String?
    public var PRIVACY_POLICY: String?
    public var TERMS_AND_CONDITIONS: String?

    public init(ABOUT_US: String?, PRIVACY_POLICY: String?, TERMS_AND_CONDITIONS: String?) {
        self.ABOUT_US = ABOUT_US
        self.PRIVACY_POLICY = PRIVACY_POLICY
        self.TERMS_AND_CONDITIONS = TERMS_AND_CONDITIONS
    }


}

